### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kprkr** [sparc-coop/law-of-100#63]
- [x] Create Meta info and card (Share link, twitter card, etc)
- [ ] Record final "scene" and edit video for launch
- [x] Write up and confirm copy for ProductHunt
- [x] Create list of sites (Free and top 3 premium) to submit to
- [x] Final visual check of all sizes/functions
- [ ] Create twitter post/media to share for official big launch
- [ ] Follow up with Noah (Original inspo for idea)

**Comment by kprkr** [comment]
Sites I will submit us to as we lead up to PH Launch (for more eyes on)

- Producthunt
- https://www.lapa.ninja/
- https://land-book.com/
- https://saaslandingpage.com/
- https://onepagelove.com/
- https://www.siteinspire.com/
- https://www.csswinner.com/ (premium)
